name: Type check with mypy

on:
  push:
    paths:
      - '*.py'

jobs:
  mypy:
    name: "Mypy type check"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - run: pip install mypy
    - run: mypy
